---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-9883c6f2
      tags:
        Env: public
        Type: test

suites:
  - name: default
    run_list:
      - recipe[singularity::default]
      - recipe[zookeeper::default]
      - recipe[zookeeper::service]
    driver:
      tags:
        Name: singularity-default-ubuntu-1404
    attributes:
      singularity:
        port: 7099
        zk_hosts:
          - 'localhost:2181'
      et_mesos:
        master:
          quorum: 1
        slave:
          attributes:
            rackid: us-east-1b
      zookeeper:
        service_style: upstart

  - name: executor_package
    run_list:
      - recipe[singularity::executor]
    driver:
      tags:
        Name: singularity-executor_package-ubuntu-1404
    attributes:
      singularity:
        executor:
          s3_bucket: example
          extra_args:
            - '-Xmx192M'
            - '-test'

  - name: executor_source
    run_list:
      - recipe[singularity::executor]
    driver:
      tags:
        Name: singularity-executor_source-ubuntu-1404
    attributes:
      singularity:
        install_type: source
        executor:
          s3_bucket: example
