---
driver:
  name: ec2
  require_chef_omnibus: 12.8
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test
    Operator: <%= ENV['USER'] %>

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[singularity::default]
    driver:
      tags:
        Name: singularity-default-ubuntu-1404
    attributes:
      singularity:
        port: 7099
        zk_hosts:
          - 'localhost:2181'
      et_mesos:
        master:
          quorum: 1
        slave:
          attributes:
            rackid: us-east-1b

  - name: sentry
    run_list:
      - recipe[singularity::default]
    driver:
      tags:
        Name: singularity-sentry-ubuntu-1404
    attribute:
      et_mesos:
        master:
          quorum: 1
        slave:
          attributes:
            rackid: us-east-1b
      singularity:
        config:
          sentry:
            dsn: http://sentry.example.com

  - name: executor_package
    run_list:
      - recipe[singularity::executor]
    driver:
      tags:
        Name: singularity-executor-package-ubuntu-1404
    attributes:
      singularity:
        executor:
          s3_bucket: example
          extra_args:
            - '-Xmx192M'
            - '-test'

  - name: executor_source
    run_list:
      - recipe[singularity::executor]
    driver:
      tags:
        Name: singularity-executor-source-ubuntu-1404
    attributes:
      singularity:
        install_type: source
        executor:
          s3_bucket: example
          extra_args:
            - '-Xmx192M'
            - '-test'
