---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      customize:
        cpus: 4
        memory: 1536
      network:
        - - private_network
          - ip: '192.168.33.10'
        - - forwarded_port
          - guest: 7099
            host: 8099
        - - forwarded_port
          - guest: 5050
            host: 8050

suites:
  - name: default
    run_list:
      - recipe[singularity::default]
      - recipe[zookeeper::default]
      - recipe[zookeeper::service]
    attributes:
      singularity:
        port: 7099
        zk_hosts:
          - 'localhost:2181'
      et_mesos:
        package:
          with_zookeeper: false
        master:
          quorum: 1
        slave:
          attributes:
            rackid: us-east-1b
      zookeeper:
        service_style: upstart

  - name: sentry
    run_list:
      - recipe[singularity::default]
    attribute:
      et_mesos:
        master:
          quorum: 1
        slave:
          attributes:
            rackid: us-east-1b
      singularity:
        config:
          sentry:
            dsn: http://sentry.example.com

  - name: executor_package
    run_list:
      - recipe[singularity::executor]
    attributes:
      singularity:
        executor:
          s3_bucket: example
          extra_args:
            - '-Xmx192M'
            - '-test'

  - name: executor_source
    run_list:
      - recipe[singularity::executor]
    attributes:
      singularity:
        install_type: source
        executor:
          s3_bucket: example
